### ISSUE TITLE
Crash after revocation of permission

### ISSUE THREAD

**Issue by Thunder7Lightening** [fabmazz/Timber#6]
When I was in this page, left picture, 
I went back to desktop screen
and then using adb to revoke storage permission.
When I went back to the app, Timber went crash.

![16370](https://user-images.githubusercontent.com/31926495/61797458-08d55880-ae5a-11e9-9237-5168d31c6ffd.png) ![317](https://user-images.githubusercontent.com/31926495/61797461-096def00-ae5a-11e9-87a8-9f6ca18f0870.png)

**Comment by fabmazz** [comment]
I will not fix bug of the app. This repo is simply a maintainance release. Since the original developer published a rewritten version of the app, I suggest you to look for it, and if you have time remove non-free stuff and publish it in F-Droid
